/*
 * GccApplication1.c
 *
 * Created: 1/12/2015 7:28:19 PM
 *  Author: DELL
 */ 


#define F_CPU 14745600
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>

#include <math.h> //included to support power function
#include "lcd.h"

///////////////////////////////////////////////////////////////////////////////////////////////Variables
// Variables for ADC conversion
unsigned char ADC_Value;    // Variable to record the digital value when ADC_conversion function is called

// Variables for sharp sensor
unsigned char sharp, distance, adc_reading;
unsigned int value;

// Variables for white line following
unsigned char flag = 0;     // Makes sure that only one if statement becomes true in one pass of the infinite loop
unsigned char Left_white_line = 0;   // Variable to store digital value from left white line sensor in the main function
unsigned char Center_white_line = 0; // Variable to store digital value from center white line sensor in the main function
unsigned char Right_white_line = 0;  // Variable to store digital value from right white line sensor in the main function

// Variables for Position Encoders
volatile unsigned long int ShaftCountLeft = 0;  //to keep track of left position encoder
volatile unsigned long int ShaftCountRight = 0; //to keep track of right position encoder
volatile unsigned int Degrees;                  //to accept angle in degrees for turning

// Variables for Color Sensor
volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red;       // variable to store the pulse count when read_red function is called
volatile unsigned long int blue;      // variable to store the pulse count when read_blue function is called
volatile unsigned long int green;     // variable to store the pulse count when read_green function is called

//////////////////////////////////////////////////////////////////////////////PIN CONFIGURATION
//Configure PORTB 5 pin for servo motor 1 operation
void servo1_pin_config (void)
{
	DDRB  = DDRB | 0x20;  //making PORTB 5 pin output            
	PORTB = PORTB | 0x20; //setting PORTB 5 pin to logic 1
}

//Configure PORTB 6 pin for servo motor 2 operation
void servo2_pin_config (void)
{
	DDRB  = DDRB | 0x40;  //making PORTB 6 pin output
	PORTB = PORTB | 0x40; //setting PORTB 6 pin to logic 1
}

//Configure PORTB 7 pin for servo motor 3 operation
void servo3_pin_config (void)
{
	DDRB  = DDRB | 0x80;  //making PORTB 7 pin output
	PORTB = PORTB | 0x80; //setting PORTB 7 pin to logic 1
}

//Function to configure LCD port
void lcd_port_config (void)
{
	DDRC = DDRC | 0xF7; //all the LCD pin's direction set as output
	PORTC = PORTC & 0x80; // all the LCD pins are set to logic 0 except PORTC 7
}

//ADC pin configuration
void adc_pin_config (void)
{
	DDRF = 0x00;
	PORTF = 0x00;
	DDRK = 0x00;
	PORTK = 0x00;
}

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFE; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x01;//Enable internal pull-up for PORTD 0 pin
}

//Function to configure ports to enable robot's motion
void motion_pin_config (void)
{
	DDRA = DDRA | 0x0F;
	PORTA = PORTA & 0xF0;
	DDRL = DDRL | 0x18;   //Setting PL3 and PL4 pins as output for PWM generation
	PORTL = PORTL | 0x18; //PL3 and PL4 pins are for velocity control using PWM.
}

//Function to configure INT4 (PORTE 4) pin as input for the left position encoder
void left_encoder_pin_config (void)
{
	DDRE  = DDRE & 0xEF;  //Set the direction of the PORTE 4 pin as input
	PORTE = PORTE | 0x10; //Enable internal pull-up for PORTE 4 pin
}

//Function to configure INT5 (PORTE 5) pin as input for the right position encoder
void right_encoder_pin_config (void)
{
	DDRE  = DDRE & 0xDF;  //Set the direction of the PORTE 4 pin as input
	PORTE = PORTE | 0x20; //Enable internal pull-up for PORTE 4 pin
}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////////////////////////INITIALIZATION
//Initialize the ports
void port_init(void)
{
	servo1_pin_config();        //Configure PORTB 5 pin for servo motor 1 operation
	servo2_pin_config();        //Configure PORTB 6 pin for servo motor 2 operation
	servo3_pin_config();        //Configure PORTB 7 pin for servo motor 3 operation
	lcd_port_config();          //LCD pin configuration
	adc_pin_config();
	color_sensor_pin_config();  //Color sensor pin cofiguration
	motion_pin_config();
	left_encoder_pin_config(); //left encoder pin config
	right_encoder_pin_config(); //right encoder pin config
}

//TIMER1 initialization in 10 bit fast PWM mode  
//prescale:256
// WGM: 7) PWM 10bit fast, TOP=0x03FF
// actual value: 52.25Hz 
void timer1_init(void)
{
 TCCR1B = 0x00; //stop
 TCNT1H = 0xFC; //Counter high value to which OCR1xH value is to be compared with
 TCNT1L = 0x01;	//Counter low value to which OCR1xH value is to be compared with
 OCR1AH = 0x03;	//Output compare Register high value for servo 1
 OCR1AL = 0xFF;	//Output Compare Register low Value For servo 1
 OCR1BH = 0x03;	//Output compare Register high value for servo 2
 OCR1BL = 0xFF;	//Output Compare Register low Value For servo 2
 OCR1CH = 0x03;	//Output compare Register high value for servo 3
 OCR1CL = 0xFF;	//Output Compare Register low Value For servo 3
 ICR1H  = 0x03;	
 ICR1L  = 0xFF;
 TCCR1A = 0xAB; /*{COM1A1=1, COM1A0=0; COM1B1=1, COM1B0=0; COM1C1=1 COM1C0=0}
 					For Overriding normal port functionality to OCRnA outputs.
				  {WGM11=1, WGM10=1} Along With WGM12 in TCCR1B for Selecting FAST PWM Mode*/
 TCCR1C = 0x00;
 TCCR1B = 0x0C; //WGM12=1; CS12=1, CS11=0, CS10=0 (Prescaler=256)
}

// Timer 5 initialized in PWM mode for velocity control
// Prescale:256
// PWM 8bit fast, TOP=0x00FF
// Timer Frequency:225.000Hz
void timer5_init()
{
	TCCR5B = 0x00;	//Stop
	TCNT5H = 0xFF;	//Counter higher 8-bit value to which OCR5xH value is compared with
	TCNT5L = 0x01;	//Counter lower 8-bit value to which OCR5xH value is compared with
	OCR5AH = 0x00;	//Output compare register high value for Left Motor
	OCR5AL = 0xFF;	//Output compare register low value for Left Motor
	OCR5BH = 0x00;	//Output compare register high value for Right Motor
	OCR5BL = 0xFF;	//Output compare register low value for Right Motor
	OCR5CH = 0x00;	//Output compare register high value for Motor C1
	OCR5CL = 0xFF;	//Output compare register low value for Motor C1
	TCCR5A = 0xA9;	/*{COM5A1=1, COM5A0=0; COM5B1=1, COM5B0=0; COM5C1=1 COM5C0=0}
 					  For Overriding normal port functionality to OCRnA outputs.
				  	  {WGM51=0, WGM50=1} Along With WGM52 in TCCR5B for Selecting FAST PWM 8-bit Mode*/
	
	TCCR5B = 0x0B;	//WGM12=1; CS12=0, CS11=1, CS10=1 (Prescaler=64)
}

void adc_init()
{
	ADCSRA = 0x00;
	ADCSRB = 0x00;		//MUX5 = 0
	ADMUX = 0x20;		//Vref=5V external --- ADLAR=1 --- MUX4:0 = 0000
	ACSR = 0x80;
	ADCSRA = 0x86;		//ADEN=1 --- ADIE=1 --- ADPS2:0 = 1 1 0
}


void left_position_encoder_interrupt_init (void) //Interrupt 4 enable
{
	cli(); //Clears the global interrupt
	EICRB = EICRB | 0x02; // INT4 is set to trigger with falling edge
	EIMSK = EIMSK | 0x10; // Enable Interrupt INT4 for left position encoder
	sei();   // Enables the global interrupt
}

void right_position_encoder_interrupt_init (void) //Interrupt 5 enable
{
	cli(); //Clears the global interrupt
	EICRB = EICRB | 0x08; // INT5 is set to trigger with falling edge
	EIMSK = EIMSK | 0x20; // Enable Interrupt INT5 for right position encoder
	sei();   // Enables the global interrupt
}

void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA = EICRA | 0x02; // INT0 is set to trigger with falling edge
	EIMSK = EIMSK | 0x01; // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////////////////////INITIALISING FUNCTION
//Function to initialize all the peripherals
void init_devices(void)
{
	cli(); //disable all interrupts
	port_init();
	timer1_init();
	timer5_init();
	adc_init();
	left_position_encoder_interrupt_init();
	right_position_encoder_interrupt_init();
	color_sensor_pin_interrupt_init();
	sei(); //re-enable interrupts
}
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////////////////////////ACTUATING FUNCTIONS
//Function For ADC Conversion
unsigned char ADC_Conversion(unsigned char Ch) 
{
	unsigned char a;
	if(Ch>7)
	{
		ADCSRB = 0x08;
	}
	Ch = Ch & 0x07;  			
	ADMUX= 0x20| Ch;	   		
	ADCSRA = ADCSRA | 0x40;		//Set start conversion bit
	while((ADCSRA&0x10)==0);	//Wait for conversion to complete
	a=ADCH;
	ADCSRA = ADCSRA|0x10; //clear ADIF (ADC Interrupt Flag) by writing 1 to it
	ADCSRB = 0x00;
	return a;
}

// This Function calculates the actual distance in millimeters(mm) from the input
// analog value of Sharp Sensor.
unsigned int Sharp_GP2D12_estimation(unsigned char adc_reading)
{
	float distance;
	unsigned int distanceInt;
	distance = (int)(10.00*(2799.6*(1.00/(pow(adc_reading,1.1546)))));
	distanceInt = (int)distance;
	if(distanceInt>800)
	{
		distanceInt=800;
	}
	return distanceInt;
}

//Function To Print Sesor Values At Desired Row And Coloumn Location on LCD
void print_sensor(char row, char coloumn,unsigned char channel)
{
	
	ADC_Value = ADC_Conversion(channel);
	lcd_print(row, coloumn, ADC_Value, 3);
}

//Function for velocity control
void velocity (unsigned char left_motor, unsigned char right_motor)
{
	OCR5AL = (unsigned char)left_motor;
	OCR5BL = (unsigned char)right_motor;
}

//Function used for setting motor's direction
void motion_set (unsigned char Direction)
{
 unsigned char PortARestore = 0;

 Direction &= 0x0F; 		// removing upper nibbel for the protection
 PortARestore = PORTA; 		// reading the PORTA original status
 PortARestore &= 0xF0; 		// making lower direction nibbel to 0
 PortARestore |= Direction; // adding lower nibbel for forward command and restoring the PORTA status
 PORTA = PortARestore; 		// executing the command
}

void forward (void) 
{
  motion_set (0x06);
}

void back (void) //both wheels backward
{
	motion_set(0x09);
}

void left (void) //Left wheel backward, Right wheel forward
{
	motion_set(0x05);
}

void right (void) //Left wheel forward, Right wheel backward
{
	motion_set(0x0A);
}

void stop (void)
{
  motion_set (0x00);
}

//ISR for color sensor
ISR(INT0_vect)
{
	pulse++; //increment on receiving pulse from the color sensor
}

//ISR for right position encoder
ISR(INT5_vect)
{
	ShaftCountRight++;  //increment right shaft position count
}


//ISR for left position encoder
ISR(INT4_vect)
{
	ShaftCountLeft++;  //increment left shaft position count
}

//Function used for turning robot by specified degrees
void angle_rotate(unsigned int Degrees)
{
	float ReqdShaftCount = 0;
	unsigned long int ReqdShaftCountInt = 0;

	ReqdShaftCount = (float) Degrees/ 4.090; // division by resolution to get shaft count
	ReqdShaftCountInt = (unsigned int) ReqdShaftCount;
	ShaftCountRight = 0;
	ShaftCountLeft = 0;

	while (1)
	{
		if((ShaftCountRight >= ReqdShaftCountInt) | (ShaftCountLeft >= ReqdShaftCountInt))
		break;
	}
	stop(); //Stop robot
}

void linear_distance_mm(unsigned int DistanceInMM)
{
	float ReqdShaftCount = 0;
	unsigned long int ReqdShaftCountInt = 0;

	ReqdShaftCount = DistanceInMM / 5.338; // division by resolution to get shaft count
	ReqdShaftCountInt = (unsigned long int) ReqdShaftCount;
	
	ShaftCountRight = 0;
	while(1)
	{
		if(ShaftCountRight > ReqdShaftCountInt)
		{
			break;
		}
	}
	stop(); //Stop robot
}

void forward_mm(unsigned int DistanceInMM)
{
	forward();
	linear_distance_mm(DistanceInMM);
}

void back_mm(unsigned int DistanceInMM)
{
	back();
	linear_distance_mm(DistanceInMM);
}

void left_degrees(unsigned int Degrees)
{
	// 88 pulses for 360 degrees rotation 4.090 degrees per count
	left(); //Turn left
	angle_rotate(Degrees);
}


void right_degrees(unsigned int Degrees)
{
	// 88 pulses for 360 degrees rotation 4.090 degrees per count
	right(); //Turn right
	angle_rotate(Degrees);
}

//Function to rotate Servo 1 by a specified angle in the multiples of 1.86 degrees
void servo_1(unsigned char degrees)
{
	float PositionPanServo = 0;
	PositionPanServo = ((float)degrees / 1.86) + 35.0;
	OCR1AH = 0x00;
	OCR1AL = (unsigned char) PositionPanServo;
}


//Function to rotate Servo 2 by a specified angle in the multiples of 1.86 degrees
void servo_2(unsigned char degrees)
{
	float PositionTiltServo = 0;
	PositionTiltServo = ((float)degrees / 1.86) + 35.0;
	OCR1BH = 0x00;
	OCR1BL = (unsigned char) PositionTiltServo;
}

//Function to rotate Servo 3 by a specified angle in the multiples of 1.86 degrees
void servo_3(unsigned char degrees)
{
	float PositionServo = 0;
	PositionServo = ((float)degrees / 1.86) + 35.0;
	OCR1CH = 0x00;
	OCR1CL = (unsigned char) PositionServo;
}

//servo_free functions unlocks the servo motors from the any angle
//and make them free by giving 100% duty cycle at the PWM. This function can be used to
//reduce the power consumption of the motor if it is holding load against the gravity.

void servo_1_free (void) //makes servo 1 free rotating
{
	OCR1AH = 0x03;
	OCR1AL = 0xFF; //Servo 1 off
}

void servo_2_free (void) //makes servo 2 free rotating
{
	OCR1BH = 0x03;
	OCR1BL = 0xFF; //Servo 2 off
}

void servo_3_free (void) //makes servo 3 free rotating
{
	OCR1CH = 0x03;
	OCR1CL = 0xFF; //Servo 3 off
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD & 0x7F; //set S3 low
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_clear(void)	//select no filter
{
	//Filter Select - no filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD & 0x7F; //set S3 Low
}

//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 20% from datasheet
	//PORTD = PORTD & 0xEF;
	PORTD = PORTD | 0x10; //set S0 high
	//PORTD = PORTD & 0xDF; //set S1 low
	PORTD = PORTD | 0x20; //set S1 high
}

void red_read(void) // function to select red filter and display the count generated by the sensor on LCD. The count will be more if the color is red. The count will be very less if its blue or green.
{
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	red = pulse;  //store the count in variable called red
	
	lcd_wr_command(0x01);
	lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Red Pulses"); // Display "Red Pulses" on LCD
	lcd_print(2,1,red,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCDlcd_cursor(1,1);  //set the cursor on row 1, column 1
}

void green_read(void) // function to select green filter and display the count generated by the sensor on LCD. The count will be more if the color is green. The count will be very less if its blue or red.
{
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
	
	lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Green Pulses"); // Display "Green Pulses" on LCD
	lcd_print(2,1,green,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
}

void blue_read(void) // function to select blue filter and display the count generated by the sensor on LCD. The count will be more if the color is blue. The count will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue

    lcd_cursor(1,1);  //set the cursor on row 1, column 1
    lcd_string("Blue Pulses"); // Display "Blue Pulses" on LCD
    lcd_print(2,1,blue,5);  //Print the count on second row
    _delay_ms(1000);	// Display for 1000ms or 1 second
    lcd_wr_command(0x01); //Clear the LCD
}

unsigned char decide_color()
{   unsigned char color = 4;
    // 0 => Terminal color is black
	// 1 => Terminal color is red
	// 2 => Terminal color is blue
	// 3 => Terminal color is green
	color_sensor_scaling();
	red_read();
	_delay_ms(500);
	blue_read();
	_delay_ms(500);
	green_read();
	_delay_ms(500);
	if(red<2000 && blue<2000 && green<2000)
	  { color = 0;
		lcd_wr_command(0x01);
		lcd_cursor(1,1);
		lcd_string("Black");
		_delay_ms(1000);
		lcd_wr_command(0x01);
	  }
	else if (red>blue && red>green)
	  { color = 1;
		lcd_wr_command(0x01);
		lcd_cursor(1,1);
		lcd_string("Red");
		_delay_ms(1000);
		lcd_wr_command(0x01);
	  }
	else if (blue>red && blue>green)
	  { color = 2;
		lcd_wr_command(0x01);
		lcd_cursor(1,1);
		lcd_string("Blue");
		_delay_ms(1000);
		lcd_wr_command(0x01);
	  }
	else if (green>red && green>blue)
	  { color = 3;
	    lcd_wr_command(0x01);
	    lcd_cursor(1,1);
	    lcd_string("Green");
	    _delay_ms(1000);
	    lcd_wr_command(0x01);
	  }
	return color;
}
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////// 

//Main function
int main(void)
{
 unsigned char i,j;
 // Pa_b => Path from a to b
 // st = start
 // 0 => Right turn
 // 1 => Left turn
 // 2 => Go straight
 // 5 => Used only as a transition element, i.e. to decide when should the robot start following the next path.
 unsigned char Pst_I3[2] = {1,5}; // 
 unsigned char PI3_I4[2] = {2,5};
 unsigned char PI4_I1[3] = {0,1,5};
 unsigned char PI1_I2[2] = {2,5};
 unsigned char PI2_T1L[5] = {0,1,0,1,5};
 unsigned char PT1L_T1R[2] = {2,5};
 unsigned char* list_of_paths[] = {Pst_I3, PI3_I4, PI4_I1, PI1_I2, PI2_T1L, PT1L_T1R};
 unsigned char* path;
 unsigned char path_var = 0;
 path = list_of_paths[path_var];
 unsigned char turn_var = -1;//0;
 
 unsigned char terminal_color;
 unsigned char terminal_color_array[4] = {4,4,4,4};
 init_devices();
 lcd_set_4bit();
 lcd_init();
 
 while(1)
 {

	 Left_white_line = ADC_Conversion(3);	//Getting data of Left WL Sensor
	 Center_white_line = ADC_Conversion(2);	//Getting data of Center WL Sensor
	 Right_white_line = ADC_Conversion(1);	//Getting data of Right WL Sensor

	 flag=0;

	 print_sensor(1,1,3);	//Prints value of White Line Sensor1
	 print_sensor(1,5,2);	//Prints Value of White Line Sensor2
	 print_sensor(1,9,1);	//Prints Value of White Line Sensor3
	 
	 lcd_print(2,1,path_var,3);
	 lcd_print(2,5,turn_var,3);
	 lcd_print(2,9,path[turn_var],3);
	 
	 sharp = ADC_Conversion(11);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
	 value = Sharp_GP2D12_estimation(sharp);            //Stores Distance calculated in a variable "value".
	 
	 if(value < 90)				
	 {
		 stop();
		 terminal_color = decide_color();
		 if(path_var<4)
		   {
		    terminal_color_array[path_var] = terminal_color;
		   }
		 _delay_ms(500);
		 velocity(200,200);
		 left_degrees(187);
		 _delay_ms(500);
		 stop();
		 _delay_ms(500);
		 back();
		 _delay_ms(800);
		 stop();
		 _delay_ms(500);
	 }
	 
	 if(Center_white_line>0x10)
	 {
		 flag=1;
		 forward();
		 velocity(210,210);
	 }

	 if((Left_white_line<0x10) && (flag==0))
	 {
		 flag=1;
		 forward();
		 velocity(190,160);
	 }

	 if((Right_white_line<0x10) && (flag==0))
	 {
		 flag=1;
		 forward();
		 velocity(160,190);
	 }

	 if((Center_white_line>30 && Left_white_line>30 && Right_white_line>30)
	    || (Center_white_line>30 && Left_white_line>30)
		|| (Center_white_line>30 && Right_white_line>30))
	 {   
		 turn_var++; // After crossing over a line, path
		 lcd_print(2,5,turn_var,3);
		 if(path[turn_var] == 5)
		 { path_var++;
		   lcd_print(2,1,path_var,3);
		   turn_var = 0;
		   lcd_print(2,5,turn_var,3);
		 }
		 lcd_print(2,9,path[turn_var],3);
		 path = list_of_paths[path_var];      // Path to be taken is decided after the robot crosses a line i.e. black comes under all three white line sensors
		 stop();
		 _delay_ms(500);
		 forward_mm(35);
		 stop();
		 _delay_ms(500);
		 if(path[turn_var] == 0)
		    { right_degrees(90);
			  velocity(175,175);
			  _delay_ms(1200);
			  stop();
			  _delay_ms(500);
			  back();
			  _delay_ms(500);
			  stop();
			  _delay_ms(500);
			}
	     else if(path[turn_var] == 1)
		    { left_degrees(90);
			  velocity(175,175);
			  _delay_ms(1200);
			  stop();
			  _delay_ms(500);
			  back();
			  _delay_ms(500);
			  stop();
			  _delay_ms(500);
			}
	     
		
	 }
     
 }
 _delay_ms(1000);
 for (i = 180,j = 0; i > 90 && j < 90; i--,j++)
    { servo_1(i);
	  _delay_ms(30);
	  servo_2(j);
	  _delay_ms(30);
	}
 _delay_ms(1000);
 for (; i > 0 && j < 180; i--,j++)
    { servo_1(i);
      _delay_ms(30);
	  servo_2(j);
	  _delay_ms(30);
	}
 _delay_ms(1000);
 for (; i < 180 && j > 0; i++,j--)	
     { servo_1(i);
       _delay_ms(30);
	   servo_2(j);
	   _delay_ms(30);
	 }
 _delay_ms(1000); 
 return 0;
}
